[package]
name = "wiki-search"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "2.0.1"
dashmap = "6.1.0"
lasso = { version = "0.7.3", features = ["multi-threaded", "serialize"] }
rayon = "1.11.0"
scraper = "0.24.0"
zim-rs = "0.1.1"
